<?php if ($this->group_path) { ?>
<div class="group_path">
<?php $group_path_index = 0; $group_path_count = count($this->group_path); ?>
<?php foreach ($this->group_path as $path_item) { ?>
<?php if (++$group_path_index == $group_path_count) { ?>
	<?= $this->escape($path_item['path_title']) ?> 
<?php } else { ?>
	<a href="<?= $path_item['path_url'] ?>"><?= $this->escape($path_item['path_title']) ?></a> :: 
<?php } ?>
<?php } ?>
</div>
<?php } ?>
<?php if ($this->group_tree) { ?>
<div class="group_tree">
<?php foreach ($this->group_tree as $group_item) { ?>
<?php if ($group_item['_depth']) { ?>
<?php for ($offset = 0; $offset < $group_item['_depth']; $offset++) { ?><div class="tree_offset"><?php } ?> 
<?php } ?>
<a href="<?= $group_item['group_url'] ?>"><?= $this->escape($group_item['group_title']) ?></a><?php if ($group_item['group_comment']) { ?>(<?= $this->escape($group_item['group_comment']) ?>)<?php } ?><br/>
<?php if ($group_item['_depth']) { ?>
<?php for ($offset = 0; $offset < $group_item['_depth']; $offset++) { ?></div><?php } ?>  
<?php } ?>
<?php } ?>
</div>
<?php } ?>
<?php if ($this->group_tree && $this->work_list) { ?>
<div class="separator"></div>
<?php } ?>
<?php if ($this->work_list) { ?>
<table class="work_table">
	<tr>
		<td>
<?php $work_list_index = 0; $work_list_count = count($this->work_list); ?>
<?php foreach ($this->work_list as $work_item) { ?>
            <?= ++$work_list_index ?>.&nbsp;&nbsp;<a href="<?= $work_item['work_url'] ?>"><?= $this->escape($work_item['work_title']) ?></a><br/>
<?php if ($work_list_index == ceil($work_list_count / 2)) { ?>
		</td>
		<td>
<?php } ?>
<?php } ?>
		</td>
	</tr>
</table>
<?php } ?>
