<?php if ($this->group_path) { ?>
<div class="group_path">
<?php $group_path_index = 0; $group_path_count = count($this->group_path); ?>
<?php foreach ($this->group_path as $path_item) { ?>
	<a href="<?= $path_item->getPathUrl() ?>"><?= $this->escape($path_item->getPathTitle()) ?></a><?php if (++$group_path_index != $group_path_count) { ?> :: <?php } ?>
<?php } ?>
</div>
<?php } ?>
<div class="work">
<h3><?= trim($this->escape($this->work_item->getWorkTitle())) ?></h3>
<p><?= rtrim(nl2br($this->work_item->getWorkText())) ?><?php if ($this->work_item->getWorkComment()) { ?><br/><br/><?= trim($this->work_item->getWorkComment()) ?><?php } ?></p>
</div>
