<?php foreach ($this->news_list as $news_item) { ?>
<div class="header">
<span class="title"><a href="<?= $news_item->getNewsUrl() ?>"><?= $news_item->getViewNewsDate() ?></a><?php if (!$news_item->getNewsPublish()) { ?>&nbsp;&nbsp;<img src="/image/design/lock.gif" alt=""/><?php } ?></span><?php foreach ($news_item->getTagList() as $tag_item) { ?>&nbsp;&nbsp;<a href="<?= $tag_item->getTagUrl() ?>" class="tag"><?= $tag_item->getTagTitle() ?></a><?php } ?> 
</div>
<div class="content">
	<?= $news_item->getNewsContent() ?>  
</div>
<div class="footer">
    <?php if ($news_item->getCommentCount()) { ?><a href="<?= $news_item->getNewsUrl() ?>">Комментариев: <?= $news_item->getCommentCount() ?></a>&nbsp;|&nbsp;<?php } ?><a href="<?= $news_item->getReplyUrl() ?>">Оставить комментарий</a>
</div>
<?php } ?>
<?php if ($this->pages) { ?>
<div class="pages">
	Страницы: <?= $this->pages ?> 
</div>
<?php } ?>
