<h3>Портфолио</h3>

<?php foreach ($this->portfolio_list as $portfolio) { ?>
    <div class="portfolio">
        <a href="<?= $portfolio->getPortfolioUrl() ?>" title="<?= $this->escape($portfolio->getPortfolioTitle()) ?>"><img src="<?= $portfolio->getPortfolioPicture() ?>" alt="<?= $this->escape($portfolio->getPortfolioTitle()) ?>"/></a><br/>
        <a href="<?= $portfolio->getPortfolioUrl() ?>"><?= $this->escape($portfolio->getPortfolioTitle()) ?></a>
	</div>
<?php } ?>
<?php if ($this->pages) { ?>
<div class="pages">
	Страницы: <?= $this->pages ?>
</div>
<?php } ?>

